### ISSUE TITLE
Flight Module pop-up won't fit on screen

### ISSUE THREAD

**Issue by millercommamatt** [samuelleblanc/fp#1]
The flight module pop-up won't fully fit on screen for a 1920x1080 display. As a result, options further down the list aren't visible.

Screenshot:
![fp_ml_module_too_tall](https://user-images.githubusercontent.com/41195794/72288049-3388b880-3616-11ea-8901-7d8116acdcee.jpg)

**Comment by samuelleblanc** [comment]
At this time, it may be better to remove some files in the flt_module directory. That would reduce the size. 

I'm working on modifying the Select_flt_mod class in gui.py to have multiple columns.

**Comment by samuelleblanc** [comment]
Made the flt_modules have  multiple columns in v1.24
