### ISSUE TITLE
Trouble Adding Flt Module

### ISSUE THREAD

**Issue by millercommamatt** [samuelleblanc/fp#3]
I downloaded version 1.24 for Windows from https://engineering.arm.gov/~sleblanc/flight_planning/ and extracted to a new folder.

I copied the new bow tie module that you just approved the PR for into the flt_module folder. It's not showing up as an option when I click on _Add flt module_.

I'm running Windows 10.

**Comment by samuelleblanc** [comment]
I can't seem to reproduce your problem. 

Make sure there is no space in the file name possibly. And that you copied both the .flt and .png files.


![image](https://user-images.githubusercontent.com/9156128/72651679-efa8f280-3938-11ea-8390-2d8fb6f36548.png)

**Comment by millercommamatt** [comment]
I installed from scratch of a different machine and added the bow tie module and it worked fine. It must be some weird case with that one machines. Thanks for trying to reproduce. IMPACTS flies it's first flight tomorrow and your software made the planning easy for me.
