### ISSUE TITLE
Trouble Deleting Points (v1.27)

### ISSUE THREAD

**Issue by millercommamatt** [samuelleblanc/fp#5]
Deleting a row from the spreadsheet is not deleting points from the map. Moving the cursor over the map isn't refreshing it and when you hit the refresh button, the deleted point is added back to the Excel file.

Editing a row will update the point in the map on mouseover.

**Comment by samuelleblanc** [comment]
Issue fixed with adding lines: 59 to 601 in excel_interface.py. Commit : 4f3a101 

Now on v1.28
